name: Fetch and parse data

on:
  push:
  workflow_dispatch:
#  schedule:
#    - cron:  '*/15 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
      
    - name: Setup python
      uses: actions/setup-python@v5
      with:
         python-version: 3.12.5
       
    - name: Setup python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install setuptools --upgrade

    - name: Fetch data via curl
      run: |
        curl -k -f https://mobie.pt/documents/42032/106470/8602.csv -o ./data/sources/mobie_tariffs.csv      
        curl -k -f https://pgm.mobie.pt/integration/nap/evChargingInfra -o ./data/sources/nap_EvChargingInfra.xml        

    - name: Run selenium test
      run: |
        python ./src/parseDatex.py

    - name: Commit and push if it changed
      run: |
        git pull
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Static data: ${timestamp}" || exit 0
        git push
